version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Test Stuff
          command: echo "PR = $CIRCLE_PULL_REQUEST , Branch = $CIRCLE_BRANCH"
